name: Docs

on:
  push:
    branches: [ master ]
    paths:
      - 'docs/**'

jobs:
  build:
    name: "OpenMod Docs"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Repository
      with:
        fetch-depth: 0
    - name: Build docs
      run: cd docs && chmod +x install-prerequisites.sh && ./install-prerequisites.sh && chmod +x build.sh && ./build.sh 
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/site