name: Publish Documentation

on:
  workflow_dispatch:
  create:
    tags:
      - "*"
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/documentation.yml'
      - 'docs/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: GitHub Pages Deployment
    steps:
    - uses: actions/checkout@v2
      name: Checkout Repository
      with:
        fetch-depth: 0
    - uses: nikeee/docfx-action@v1.0.0
      name: Build Documentation
      with:
        args: docs/docfx.json
    - uses: peaceiris/actions-gh-pages
      name: Publish Documentation on GitHub Pages
      env:
        publish_dir: docs/_site
        github_token: ${{ secrets.GITHUB_TOKEN }}
        external_repository: openmod/openmod-docs