name: OpenMod.Standalone

on:
  create:
    tags:
      - *
  push:
    branches: [ master ]
    paths:
      - 'standalone/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'standalone/**'

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Repository
      with:
        fetch-depth: 0
    - name: Extract version
      id: get_version
      run: echo ::set-output name=VERSION::$(git describe --tags)        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore standalone/OpenMod.Standalone
    - name: Update version
      run: "sed -i \"s#<Version>0.0.0</Version>#<Version>${{ steps.get_version.outputs.VERSION }}</Version>#\" props/SharedProjectProps.props"  
    - name: Build
      run: dotnet build standalone/OpenMod.Standalone --configuration Release --no-restore
#    - name: Test
#      run: dotnet test --no-restore --verbosity normal
    - name: Create release
      if: github.event_name == 'created' && github.event.ref_type == 'tag'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}_standalone
        release_name: Standalone Release v${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false   
    - name: Zip net461 artifacts
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -b ./standalone/OpenMod.Standalone/bin/Release/net461 -r ./release-net461.zip * 
    - name: Zip netcoreapp3.1 artifacts
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -b ./standalone/OpenMod.Standalone/bin/Release/netcoreapp3.1 -r ./release-netcoreapp3.1.zip *
    - name: Upload net461 release asset
      if: github.event_name == 'created' && github.event.ref_type == 'tag'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release-net461.zip
        asset_name: OpenMod.Standalone-v${{ steps.get_version.outputs.VERSION }}-net461.zip
        asset_content_type: application/zip
    - name: Upload netcoreapp3.1 release asset
      if: github.event_name == 'created' && github.event.ref_type == 'tag'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release-netcoreapp3.1.zip
        asset_name: OpenMod.Standalone-v${{ steps.get_version.outputs.VERSION }}-netcoreapp3.1.zip
        asset_content_type: application/zip        