name: OpenMod.Unturned.Module

on:
  push:
    branches: [ master ]
    paths:
      - 'framework/OpenMod.Unturned.Module/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'framework/OpenMod.Unturned.Module/**'

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:    
    - name: Wait version tag
      if: github.event_name != 'pull_request'
      uses: fountainhead/action-wait-for-check@v1.0.0
      id: wait-for-build
      with:
        token: ${{ secrets.GH_TOKEN }}
        checkName: "bumpVersion"
        owner: 'openmod'
        repo: 'OpenMod'
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
    - uses: actions/checkout@v2
      name: Checkout Repository
      with:
        fetch-depth: 0
    - name: Extract version
      id: get_version
      run: echo ::set-output name=VERSION::$(git describe --tags)          
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore framework/OpenMod.Unturned.Module
    - name: Update version
      run: "sed -i \"s#<Version>0.0.0</Version>#<Version>${{ steps.get_version.outputs.VERSION }}</Version>#\" props/SharedProjectProps.props"  
    - name: Build
      run: dotnet build framework/OpenMod.Unturned.Module --configuration Release --no-restore
#    - name: Test
#      run: dotnet test --no-restore --verbosity normal
    - name: Zip artifacts
      uses: montudor/action-zip@v0.1.0
      with:
      args: zip -qq -r ./release.zip ./framework/OpenMod.Unturned.Module/bin/Release/net461
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: Release v${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false   
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release.zip
        asset_name: OpenMod.Unturned.Module-v${{ steps.get_version.outputs.VERSION }}.zip
        asset_content_type: application/zip