name: OpenMod.Unturned.Module

on:
  create:
    tags:
      - "*"
  push:
    branches: [ master ]
    paths:
      - 'framework/**'
      - 'unityengine/**'      
      - 'unturned/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'framework/**'
      - 'unityengine/**'      
      - 'unturned/**'

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
      name: Checkout Repository
      with:
        fetch-depth: 0
    - name: Extract version
      id: get_version
      run: echo ::set-output name=VERSION::$(git describe --tags)     
    - name: Setup  mono
      run: sudo apt-get install mono-complete 
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore unturned/OpenMod.Unturned.Module
    - name: Update version
      run: "sed -i \"s#<Version>0.0.0</Version>#<Version>${{ steps.get_version.outputs.VERSION }}</Version>#\" props/SharedProjectProps.props"  
    - name: Build
      run: dotnet build unturned/OpenMod.Unturned.Module --configuration Release --no-restore
#    - name: Test
#      run: dotnet test --no-restore --verbosity normal
    - name: Install zip
      if: github.event_name == 'create' && github.event.ref_type == 'tag'
      run: sudo apt-get install zip
    - name: Zip artifacts
      if: github.event_name == 'create' && github.event.ref_type == 'tag'
      run: "cd ./unturned/OpenMod.Unturned.Module/bin/Release/net461 && zip -qq -r ./release.zip *"
    - name: Create release
      if: github.event_name == 'create' && github.event.ref_type == 'tag'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}_unturned
        release_name: Unturned Release v${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false   
    - name: Upload release asset
      if: github.event_name == 'create' && github.event.ref_type == 'tag'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./unturned/OpenMod.Unturned.Module/bin/Release/net461/release.zip
        asset_name: OpenMod.Unturned.Module-v${{ steps.get_version.outputs.VERSION }}.zip
        asset_content_type: application/zip